---
fontsize: 12pt
output:
  html_document:
    smart: no
---

## 5_hrs_analysis.Rmd

Load packages in order of use.

```{r message = FALSE}
library(package = knitr)     # dynamic reports
library(package = rprojroot) # find absolute file-path of root directory
library(package = readr)     # import and export data
library(package = dplyr)     # transform data
```

Load package options.

```{r}
opts_chunk$set(comment = "")
```

Locate in-put data.

```{r}
root_path <- find_root(criterion = "README.md",
                       path = ".")

import_path <- paste(root_path,
                     "/hrs.tsv",
                     sep = "",
                     collapse = "")
```

Import in-put data.

```{r message = FALSE}
hrs <- read_tsv(file = import_path,
                col_names = TRUE,
                col_types = NULL,
                locale = default_locale(),
                na = "",
                quoted_na = TRUE,
                comment = "",
                trim_ws = TRUE,
                skip = 0,
                n_max = Inf,
                guess_max = 1000,
                progress = TRUE)
```